# Generated by Django 3.0.7 on 2020-07-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20200706_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='', max_length=200)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetail')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websites.WebsiteName')),
            ],
        ),
    ]
