# Generated by Django 3.0.7 on 2020-07-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitename',
            name='userID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
