# Generated by Django 3.0.7 on 2020-06-25 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='password',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='userID',
            new_name='gmailID',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='username',
            new_name='googleAuthID',
        ),
        migrations.RenameField(
            model_name='userdetail',
            old_name='website',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='phoneNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.CreateModel(
            name='WebsiteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='', max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.UserDetail')),
            ],
        ),
    ]
