# Generated by Django 3.0.7 on 2020-06-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200625_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebsiteDetails',
            new_name='WebsiteDetail',
        ),
    ]
