# Generated by Django 3.0.7 on 2020-07-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200706_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteuserdetail',
            name='website',
        ),
        migrations.DeleteModel(
            name='WebsiteName',
        ),
        migrations.DeleteModel(
            name='WebsiteUserDetail',
        ),
    ]
